[package]
name = "heated_words"
version = "0.7.0"
authors = ["Sevaarcen <coleipod@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = {version = "0.10", features = ["blocking"] }
url = "1.7.2"
regex = "1.1.0"
config = "0.9.1"
lazy_static = "1.2.0"
clap = "2.32.0"
futures = "0.3"