[package]
name = "HeatedWords"
version = "0.4.2"
authors = ["Sevaarcen <coleipod@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.5"
url = "1.7.2"
regex = "1.1.0"
config = "0.9.1"
lazy_static = "1.2.0"
