debug = false

# settings to change what links are processed for the wordlist
[sensitivity]
max_links = 6 #max links returned by each engine. -1 for unlimited
match_threshold = 0.60 # N percent of the words in the query should match the link
extra_threshold = 0.80 # max N percent of the words in the link that doesn't match a word in the query

[filenames]
links = "links.txt"
wordlist = "wordlist.txt"

[engines]
    [engines.google]
    url = "https://www.google.com/search?q={}" # "{}" gets substituted for the query
    regex = '<h3 class="r"><a href="/url\?q={}&amp;' # "{}" gets susbtituted for the regex extracting the link itself (lazy)

    [engines.wikipedia]
    url = "https://en.wikipedia.org/w/index.php?search={}!" # has a "!" at the end so it won't match a wiki page exactly
    regex = '''<div class='mw-search-result-heading'><a href="{}['"][ >]''' #multiline so we can use the ' character

#currently there is no interface directly from this program to another one
#data must be collected from the files themselves, which will be written before post-processing is run
[post-processing]
    [post-processing.test]
    description = "tests post-processing functionality"
    command = "cmd"
    args = ["/C", "echo Hello there from post-processing as defined in config.toml!"]

    [post-processing.malformed1] #this suceeds because "description" is optional
    desc = "bad desc"
    command = "cmd"
    args = ["/C", "echo", "malformed commands might still work!"]

    [post-processing.malformed2] #this fails
    description = "bad boii!!!!"
    command = "ljkaibesfkljhbwaekjfhbakj"
    args = []