debug = false
minimum_word_length = 6 #inclusive minimum limit
maximum_word_length = 14 #inclusive maximum limit

# My current UA in Firefox as of 2020-01-02
user-agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"

# settings to change what links are processed for the wordlist
[sensitivity]
max_links = 6 #max links returned by each engine. -1 for unlimited
match_threshold = 0.60 # N percent of the words in the query should match the link
extra_threshold = 0.80 # max N percent of the words in the link that doesn't match any word in the query
word_bypass_limit = 2 # If the number of words in the page URL is less than to the number of words in the query and less than/equal this, it will bypass the QA check
# ignore any of these patterns (regex) that occur in the URL (minus domain) when performing the QA check
ignore_link_patterns = [
    "wiki",
    "%[0-9]{2}",
    "htm[l]?",
    "asp[x]?"
]

[filenames]
links = "links.txt"
wordlist = "wordlist.txt"

[engines]
    [engines.google]
    url = "https://www.google.com/search?q={}" # "{}" gets substituted for the query
    regex = '<a href="(?P<link>http[^"]+?)" onmousedown' # must contain a capture group called "link"

    [engines.wikipedia]
    url = "https://en.wikipedia.org/w/index.php?search={}!" # has a "!" at the end so it won't match a wiki page exactly
    regex = '''<a href="(?P<link>/wiki/[^"]+?)" title="[^"]{1,100}" data-serp-pos="[0-9]{1,3}">''' #multiline so we can use the ' character

#currently there is no interface directly from this program to another one
#data must be collected from the files themselves, which will be written before post-processing is run
[post-processing]
    #[post-processing.test]
    #description = "post-processing functionality test" #optional key
    #command = "cmd"
    #args = ["/C", "echo Hello there from post-processing as defined in config.toml!"] #optional key, but typically always needed